export interface ClientLogo {
  name: string;
  src: string;
}

export const featuredClientLogos: ClientLogo[] = [
  { name: "ThoughtWorks", src: "/website/assets/client-logos/featured/01_ThoughtWorks.png" },
  { name: "DBS", src: "/website/assets/client-logos/featured/02_DBS.png" },
  { name: "Bajaj Life", src: "/website/assets/client-logos/featured/03_Bajaj_Allianz_Life_Insurance.png" },
  { name: "Aditya Birla Group", src: "/website/assets/client-logos/featured/04_Aditya_Birla_Sun_Life_AMC.png" },
  { name: "AT&T", src: "/website/assets/client-logos/featured/05_AT_and_T.png" },
  { name: "Accordion Partners", src: "/website/assets/client-logos/featured/06_Accordion_Partners.png" },
  { name: "PwC", src: "/website/assets/client-logos/featured/07_PwC.png" },
  { name: "Amdocs", src: "/website/assets/client-logos/featured/10_Amdocs.png" },
  { name: "Aditya Birla Capital Stocks & Securities", src: "/website/assets/client-logos/featured/11_Aditya_Birla_Money.png" },
  { name: "JSW", src: "/website/assets/client-logos/featured/13_JSW.png" },
  { name: "CSB Bank", src: "/website/assets/client-logos/featured/14_CSB_Bank.png" },
  { name: "KPI Partners", src: "/website/assets/client-logos/featured/15_KPI_Partners.png" },
  { name: "Decision Minds", src: "/website/assets/client-logos/featured/16_Decision_Minds.png" },
  { name: "Essar Group", src: "/website/assets/client-logos/featured/17_Essar_Group.png" },
  { name: "Mesa School of Business", src: "/website/assets/client-logos/featured/20_Mesa_School_of_Business.png" },
  { name: "Flipkart", src: "/website/assets/client-logos/featured/21_Flipkart.png" },
  { name: "HDFC Bank", src: "/website/assets/client-logos/featured/22_HDFC_Bank.png" },
  { name: "Vedanta", src: "/website/assets/client-logos/featured/23_Vedanta.png" },
  { name: "Uno Minda", src: "/website/assets/client-logos/featured/24_Uno_Minda.png" },
  { name: "Ali & Sons", src: "/website/assets/client-logos/featured/25_Ali_and_Sons.png" },
  { name: "Myntra", src: "/website/assets/client-logos/featured/26_Myntra.png" },
  { name: "Bajaj Health", src: "/website/assets/client-logos/featured/27_Bajaj_Finserv_Health.png" },
  { name: "Cholamandalam Investment and Finance Company", src: "/website/assets/client-logos/featured/29_Cholamandalam_Investment_and_Finance_Company.png" },
  { name: "Coromandel International", src: "/website/assets/client-logos/featured/31_Coromandel_International.png" },
  { name: "Mahindra Finance", src: "/website/assets/client-logos/featured/37_Mahindra_Finance.png" },
  { name: "Hero FinCorp", src: "/website/assets/client-logos/featured/38_Hero_Fincorp.png" },
];

export const archiveClientLogos: ClientLogo[] = [
  { name: "Walmart Global Tech", src: "/website/assets/client-logos/archive/001.webp" },
  { name: "Oracle", src: "/website/assets/client-logos/archive/002.webp" },
  { name: "J.P. Morgan", src: "/website/assets/client-logos/archive/003.webp" },
  { name: "Mastercard", src: "/website/assets/client-logos/archive/004.webp" },
  { name: "American Express", src: "/website/assets/client-logos/archive/005.webp" },
  { name: "Shell", src: "/website/assets/client-logos/archive/006.webp" },
  { name: "Sony", src: "/website/assets/client-logos/archive/007.webp" },
  { name: "HSBC", src: "/website/assets/client-logos/archive/008.webp" },
  { name: "Verizon", src: "/website/assets/client-logos/archive/009.webp" },
  { name: "NTT Group", src: "/website/assets/client-logos/archive/010.webp" },
  { name: "John Deere", src: "/website/assets/client-logos/archive/011.webp" },
  { name: "S&P Global", src: "/website/assets/client-logos/archive/012.webp" },
  { name: "BNP Paribas", src: "/website/assets/client-logos/archive/013.webp" },
  { name: "Deutsche Bank", src: "/website/assets/client-logos/archive/014.webp" },
  { name: "DHL", src: "/website/assets/client-logos/archive/015.webp" },
  { name: "Diageo", src: "/website/assets/client-logos/archive/016.webp" },
  { name: "Ericsson", src: "/website/assets/client-logos/archive/017.webp" },
  { name: "General Mills", src: "/website/assets/client-logos/archive/018.webp" },
  { name: "Emerson", src: "/website/assets/client-logos/archive/019.webp" },
  { name: "Invesco", src: "/website/assets/client-logos/archive/020.webp" },
  { name: "IGT", src: "/website/assets/client-logos/archive/021.webp" },
  { name: "Hitachi Vantara", src: "/website/assets/client-logos/archive/022.webp" },
  { name: "Merck", src: "/website/assets/client-logos/archive/023.webp" },
  { name: "MSCI", src: "/website/assets/client-logos/archive/024.webp" },
  { name: "Northern Trust", src: "/website/assets/client-logos/archive/025.webp" },
  { name: "Royal Bank of Scotland", src: "/website/assets/client-logos/archive/026.webp" },
  { name: "Silicon Valley Bank", src: "/website/assets/client-logos/archive/027.webp" },
  { name: "Thales", src: "/website/assets/client-logos/archive/028.webp" },
  { name: "Tata Motors", src: "/website/assets/client-logos/archive/029.webp" },
  { name: "Xiaomi", src: "/website/assets/client-logos/archive/030.webp" },
  { name: "EPAM", src: "/website/assets/client-logos/archive/031.webp" },
  { name: "Springer Nature", src: "/website/assets/client-logos/archive/032.webp" },
  { name: "Adani", src: "/website/assets/client-logos/archive/033.webp" },
  { name: "Aditya Birla Capital", src: "/website/assets/client-logos/archive/034.webp" },
  { name: "ANZ", src: "/website/assets/client-logos/archive/035.webp" },
  { name: "Biocon", src: "/website/assets/client-logos/archive/036.webp" },
  { name: "Blue Yonder", src: "/website/assets/client-logos/archive/037.webp" },
  { name: "BMC Software", src: "/website/assets/client-logos/archive/038.webp" },
  { name: "Concerto", src: "/website/assets/client-logos/archive/039.webp" },
  { name: "Cyient", src: "/website/assets/client-logos/archive/040.webp" },
  { name: "Ericsson", src: "/website/assets/client-logos/archive/041.webp" },
  { name: "Eurofins", src: "/website/assets/client-logos/archive/042.webp" },
  { name: "EXL", src: "/website/assets/client-logos/archive/043.webp" },
  { name: "FactSet", src: "/website/assets/client-logos/archive/044.webp" },
  { name: "Fidelity Investments", src: "/website/assets/client-logos/archive/045.webp" },
  { name: "Fidelity International", src: "/website/assets/client-logos/archive/046.webp" },
  { name: "Finastra", src: "/website/assets/client-logos/archive/047.webp" },
  { name: "FIS", src: "/website/assets/client-logos/archive/048.webp" },
  { name: "Fiserv", src: "/website/assets/client-logos/archive/049.webp" },
  { name: "Fujitsu", src: "/website/assets/client-logos/archive/050.webp" },
  { name: "Future Generali", src: "/website/assets/client-logos/archive/051.webp" },
  { name: "GEP", src: "/website/assets/client-logos/archive/052.webp" },
  { name: "GlobalLogic", src: "/website/assets/client-logos/archive/053.webp" },
  { name: "GXO", src: "/website/assets/client-logos/archive/054.webp" },
  { name: "Gyansys", src: "/website/assets/client-logos/archive/055.webp" },
  { name: "Happiest Minds", src: "/website/assets/client-logos/archive/056.webp" },
  { name: "Harman", src: "/website/assets/client-logos/archive/057.webp" },
  { name: "Hexaware Technologies", src: "/website/assets/client-logos/archive/058.webp" },
  { name: "HighRadius", src: "/website/assets/client-logos/archive/059.webp" },
  { name: "JLL Technologies", src: "/website/assets/client-logos/archive/060.webp" },
  { name: "Ingram Micro", src: "/website/assets/client-logos/archive/061.webp" },
  { name: "InfrasoftTech", src: "/website/assets/client-logos/archive/062.webp" },
  { name: "Infor", src: "/website/assets/client-logos/archive/063.webp" },
  { name: "InfoBeans", src: "/website/assets/client-logos/archive/064.webp" },
  { name: "Incedo", src: "/website/assets/client-logos/archive/065.webp" },
  { name: "Indegene", src: "/website/assets/client-logos/archive/066.webp" },
  { name: "Incture Technologies", src: "/website/assets/client-logos/archive/067.webp" },
  { name: "Impetus", src: "/website/assets/client-logos/archive/068.webp" },
  { name: "Larsen & Toubro", src: "/website/assets/client-logos/archive/069.webp" },
  { name: "LogicMonitor", src: "/website/assets/client-logos/archive/070.webp" },
  { name: "Lumen", src: "/website/assets/client-logos/archive/071.webp" },
  { name: "Marlabs", src: "/website/assets/client-logos/archive/072.webp" },
  { name: "Mastek", src: "/website/assets/client-logos/archive/073.webp" },
  { name: "Mavenir", src: "/website/assets/client-logos/archive/074.webp" },
  { name: "Mindtree", src: "/website/assets/client-logos/archive/075.webp" },
  { name: "Morningstar", src: "/website/assets/client-logos/archive/076.webp" },
  { name: "Netmagic", src: "/website/assets/client-logos/archive/077.webp" },
  { name: "NICE", src: "/website/assets/client-logos/archive/078.webp" },
  { name: "Nomura", src: "/website/assets/client-logos/archive/079.webp" },
  { name: "NSE", src: "/website/assets/client-logos/archive/080.webp" },
  { name: "Omnicell", src: "/website/assets/client-logos/archive/081.webp" },
  { name: "Orion Business Innovation", src: "/website/assets/client-logos/archive/082.webp" },
  { name: "Piramal", src: "/website/assets/client-logos/archive/083.webp" },
  { name: "Pitney Bowes", src: "/website/assets/client-logos/archive/084.webp" },
  { name: "MassMutual", src: "/website/assets/client-logos/archive/085.webp" },
  { name: "Publicis Sapient", src: "/website/assets/client-logos/archive/086.webp" },
  { name: "Quinnox", src: "/website/assets/client-logos/archive/087.webp" },
  { name: "Rackspace Technology", src: "/website/assets/client-logos/archive/088.webp" },
  { name: "Ramco", src: "/website/assets/client-logos/archive/089.webp" },
  { name: "Reltio", src: "/website/assets/client-logos/archive/090.webp" },
  { name: "Riversand", src: "/website/assets/client-logos/archive/091.webp" },
  { name: "Sahyadri Hospitals", src: "/website/assets/client-logos/archive/092.webp" },
  { name: "Sasken", src: "/website/assets/client-logos/archive/093.webp" },
  { name: "Saviynt", src: "/website/assets/client-logos/archive/094.webp" },
  { name: "Sella", src: "/website/assets/client-logos/archive/095.webp" },
  { name: "Sonata Software", src: "/website/assets/client-logos/archive/096.webp" },
  { name: "Sopra Steria", src: "/website/assets/client-logos/archive/097.webp" },
  { name: "Speridian Technologies", src: "/website/assets/client-logos/archive/098.webp" },
  { name: "Stridely Solutions", src: "/website/assets/client-logos/archive/099.webp" },
  { name: "Sutherland", src: "/website/assets/client-logos/archive/100.webp" },
  { name: "Synechron", src: "/website/assets/client-logos/archive/101.webp" },
  { name: "Synoptek", src: "/website/assets/client-logos/archive/102.webp" },
  { name: "Sopra Banking Software", src: "/website/assets/client-logos/archive/103.webp" },
  { name: "Principal", src: "/website/assets/client-logos/archive/104.webp" },
  { name: "Unisys", src: "/website/assets/client-logos/archive/105.webp" },
  { name: "UKG", src: "/website/assets/client-logos/archive/106.webp" },
  { name: "Tricentis", src: "/website/assets/client-logos/archive/107.webp" },
  { name: "Tesco", src: "/website/assets/client-logos/archive/108.webp" },
  { name: "Tech Mahindra", src: "/website/assets/client-logos/archive/109.webp" },
  { name: "Telstra", src: "/website/assets/client-logos/archive/110.webp" },
  { name: "Tata Power", src: "/website/assets/client-logos/archive/111.webp" },
  { name: "Tata Technologies", src: "/website/assets/client-logos/archive/112.webp" },
  { name: "Tata Elxsi", src: "/website/assets/client-logos/archive/113.webp" },
  { name: "ValueLabs", src: "/website/assets/client-logos/archive/114.webp" },
  { name: "Western Digital", src: "/website/assets/client-logos/archive/115.webp" },
  { name: "WNS", src: "/website/assets/client-logos/archive/116.webp" },
  { name: "WSP", src: "/website/assets/client-logos/archive/117.webp" },
  { name: "YASH Technologies", src: "/website/assets/client-logos/archive/118.webp" },
  { name: "Zensar Technologies", src: "/website/assets/client-logos/archive/119.webp" },
  { name: "Amadeus", src: "/website/assets/client-logos/archive/120.webp" },
  { name: "Baker Hughes", src: "/website/assets/client-logos/archive/121.webp" },
  { name: "Birlasoft", src: "/website/assets/client-logos/archive/122.webp" },
  { name: "Bitwise", src: "/website/assets/client-logos/archive/123.webp" },
  { name: "CGI", src: "/website/assets/client-logos/archive/124.webp" },
  { name: "Capgemini", src: "/website/assets/client-logos/archive/125.webp" },
  { name: "eClerx", src: "/website/assets/client-logos/archive/126.webp" },
  { name: "EY", src: "/website/assets/client-logos/archive/127.webp" },
  { name: "KPIT", src: "/website/assets/client-logos/archive/128.webp" },
  { name: "Persistent", src: "/website/assets/client-logos/archive/129.webp" },
  { name: "Quantiphi", src: "/website/assets/client-logos/archive/130.webp" },
  { name: "Bosch", src: "/website/assets/client-logos/archive/131.webp" },
  { name: "Xoriant", src: "/website/assets/client-logos/archive/132.webp" },
];
